/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=develop --include-runtime=false worker/cloudflare-env.d.ts` (hash: 273d745d0800d0f10842f05796e2a968)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  APP_BASE_PATH: '/dev/RoomPlaner';
  DEPLOYMENT: 'develop';
  DEV_PASSWORD: string;
  LOGIN_GUARD: DurableObjectNamespace<import('./index').LoginGuard>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
    durableNamespaces: 'LoginGuard';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'APP_BASE_PATH' | 'DEPLOYMENT' | 'DEV_PASSWORD'>
  > {}
}
